parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
settings:
  react:
    version: detect
env:
  es6: true
  node: true
globals:
  __DEV__: false
rules:
  curly: error
  no-console: off
  react/prop-types: off
  react/display-name: off
overrides:
  - files:
      - babel.config.js
      - jest.config.js
      - playground/rn-cli.config.js
    env:
      node: true
  - files:
      - tests/*.js
    env:
      jest: true
