parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
plugins:
  - flowtype
env:
  es6: true
  node: true
rules:
  curly: error
  react/prop-types: off
  flowtype/define-flow-type: warn
overrides:
  - files:
      - babel.config.js
      - jest.config.js
      - playground/rn-cli.config.js
    env:
      node: true
  - files:
     - tests/*.js
    env:
      jest: true
