language: node_js
node_js: node
cache:
  yarn: true
  directories:
    - node_modules
    - playground/node_modules
matrix:
  - JOB=test
  - JOB=lint
before_script:
  - cd playground/ && yarn && cd ..
script:
  - eslint .
  - prettier --list-different README.md
  - jest --coverage
  - codecov
